name: My Code for upload

on: pull
jobs:
  build:
    name: Start coding ...
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    
    steps:
       - name: Setup and run build
         run: |
          git config --global user.name "Github Actions";git config --global user.email "actions@github.com"
          git clone https://${{ secrets.tok}}@github.com/iamtelegramking/myuploader.git
          git clone https://github.com/iamtelegramking/mycodeworks
          cp mycodeworks/mydata.bin myuploader/mydata.bin
          cd myuploader;pip3 install -r requirements.txt;python3 mycode.py
          
